In [2]:
#The simplest way to represent vectors in Python is using a list structure.
x = [-1.1, 0.0, 3.6, -7.2]
len(x)

4

In [3]:
x = (-1.1, 0.0, 3.6, -7.2) #Its a tuple of consisting four elements and not a vector


In [4]:
#Another common way to represent vectors in Python is to use a numpy array. To do so,
#we must first import the numpy package.
import numpy as np
x = np.array([-1.1, 0.0, 3.6, -7.2])
len(x)

4

In [5]:
x[3]

-7.2

In [6]:
x = np.array([1,8,3,2,1,9,7])
d = x[1:] - x[:-1]
print(d)

[ 7 -5 -1 -1  8 -2]


In [7]:
#Vector Addition and Subtraction:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([100, 200, 300])
print(x+y)
print(x-y)

[101 202 303]
[ -99 -198 -297]


In [8]:
import numpy as np
x = np.array([1,2,3])
print(2.2*x)

[2.2 4.4 6.6]


In [9]:
import numpy as np
x = np.array([1,2,3])
print(x/2.2)

[0.45454545 0.90909091 1.36363636]


In [10]:
#Linear combination:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
alpha = -0.5
beta = 1.5
c = alpha*a + beta*b
print(c)

[4. 5.]


In [11]:
#The inner product of n-vector x and y:
import numpy as np
x = np.array([-1,2,2])
y = np.array([1,0,-3])
print(np.inner(x,y))

-7


In [12]:
#Alternative way:
import numpy as np
x = np.array([-1,2,2])
y = np.array([1,0,-3])
x @ y

-7

In [13]:
#Norm (length) of a vector:
x = np.array([2,-1,2])
print(np.linalg.norm(x))

3.0


In [14]:
#Distance between two vectors:
u = np.array([1.8, 2.0, -3.7, 4.7])
v = np.array([0.6, 2.1, 1.9, -1.4])
print(np.linalg.norm(u-v))

8.367795408588812


In [15]:
#Orthonormal Vectors:
a1 = np.array([0,0,-1])
a2 = np.array([1,1,0])/(2)**0.5
a3 = np.array([1,-1,0])/(2)**0.5
print('Norm of a1:', (sum(a1**2))**0.5)
print('Norm of a2:', (sum(a2**2))**0.5)
print('Norm of a3:', (sum(a3**2))**0.5)

Norm of a1: 1.0
Norm of a2: 0.9999999999999999
Norm of a3: 0.9999999999999999


In [17]:
print(a1 @ a2, a1 @ a3, a2 @ a3)

0.0 0.0 -2.2371143170757382e-17


In [18]:
#Coefficients in orthonormal basis:
x = np.array([1,2,3])
#Get coefficients of x in orthonormal basis
beta1 = a1 @ x
beta2 = a2 @ x
beta3 = a3 @ x
#Expansion of x in basis
x_expansion = beta1*a1 + beta2*a2 + beta3*a3
print(x_expansion)

[1. 2. 3.]


In [19]:
import numpy as np
A=np.array([[1,2,3],[2, -1, 1]])
print(A)

[[ 1  2  3]
 [ 2 -1  1]]


In [20]:
A.shape

(2, 3)

In [21]:
A[0,0]

1

In [22]:
A[0,:]

array([1, 2, 3])

In [35]:
B=np.array([[1, 2, -1],[2, 2, 2], [1, 3, 2]])
print(B)

[[ 1  2 -1]
 [ 2  2  2]
 [ 1  3  2]]


In [36]:
print(np.linalg.det(B))

-10.000000000000002


In [37]:
eval, evec =np.linalg.eig(B)
print(eigen)

(array([ 4.77016191,  1.56735537, -1.33751728]), array([[-0.14322508, -0.71511923,  0.69072431],
       [-0.64521769,  0.13959725, -0.62836086],
       [-0.75045367,  0.68492123,  0.3578583 ]]))


In [38]:
print(eval)


[ 4.77016191  1.56735537 -1.33751728]


In [39]:
print(evec)

[[-0.14322508 -0.71511923  0.69072431]
 [-0.64521769  0.13959725 -0.62836086]
 [-0.75045367  0.68492123  0.3578583 ]]


In [46]:
evec1 = np.array([-0.14322508, -0.64521769,  -0.75045367])
np.linalg.norm(evec1)
4.77016191*evec1

array([-0.68320682, -3.07779285, -3.57978551])

In [45]:
vector1 = 1*evec1
np.dot(B,evec1)

array([-0.68320679, -3.07779288, -3.57978549])

In [ ]:
C=np.array([[1.5, .5], [1.5, .5]])
print(C)

In [ ]:
eval, evec=np.linalg.eig(C)

In [ ]:
print(eval)

In [ ]:
print(np.linalg.det(C))

In [ ]:
D=np.array([[2, 1], [-1, 2]])
print(D)

In [ ]:
eval, evec=np.linalg.eig(D)

In [ ]:
print(eval)