In [8]:
import numpy as np

In [4]:
data = []
calls = [0,1,2,3,4,5,6,7]
frequency = [14,21,25,43,51,40,39,12]
for i in range(len(calls)):
    for j in range(frequency[i]):
        data.append(calls[i])      
    

In [12]:
#print(data)
totalFrequency = sum(frequency)
print(totalFrequency)

245


In [11]:
print(np.mean(data))
print(np.median(data))
#np.range(data)
print(np.std(data))
print(np.var(data))

3.763265306122449
4.0
1.8585372652565662
3.4541607663473557


In [13]:
3.4541607663473557*245

846.2693877551021

In [14]:
import numpy as np

arr = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]])

print(arr)


[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
